/*
 * FILE : pdflib_java.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.2 (alpha 1)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : Java*/

#include <jni.h>
#include <stdlib.h>

#ifdef __cplusplus
#define JCALL(func, jenv) jenv->func(
#else
#define JCALL(func, jenv) (*jenv)->func(jenv,
#endif

static jobject JObjectFromPointer(JNIEnv *jenv, char *className, void *p) {
  jclass jc;
  jmethodID jmid;
  jobject jresult;
  jlong jl;

  if(p == NULL) return NULL;

  jc = JCALL(FindClass, jenv) className);
  if(jc == NULL) return NULL;
  jmid = JCALL(GetStaticMethodID, jenv) jc, "initializeFromPointer", "(J)Ljava/lang/Object;");
  if(jmid == NULL) return NULL;
  
  *(void **) &jl = p;
  jresult = JCALL(CallStaticObjectMethod, jenv) jc, jmid, jl);

  return jresult;
}

static void *PointerFromJObject(JNIEnv *jenv, jobject jo) {
  jclass jc;
  jmethodID jmid;
  jlong jl;

  if(jo == NULL) return NULL;

  jc = JCALL(GetObjectClass, jenv) jo);
  jmid = JCALL(GetMethodID, jenv) jc, "self", "()J");
  jl = JCALL(CallLongMethod, jenv) jo, jmid);

  return *(void **)&jl;
}

#define J_CLASSNAME pdflib
#define J_PACKAGE

#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99

#include <setjmp.h>

/* The following sick stuff is an attempt to make recent Perl versions
 * work with recent SWIG versions compiled with recent MS VC++ versions.
 */
#ifdef _MSC_VER
    #undef setjmp
    #define setjmp _setjmp
    #undef longjmp
#endif

#include "pdflib.h"

/* Map PDFlib errors to SWIG exceptions */
static const int pdf_swig_exceptions[] = {
    0,
    SWIG_MemoryError,	/* PDF_MemoryError    1 */
    SWIG_IOError,	/* PDF_IOError        2 */
    SWIG_RuntimeError,	/* PDF_RuntimeError   3 */
    SWIG_IndexError,	/* PDF_IndexError     4 */
    SWIG_TypeError,	/* PDF_TypeError      5 */
    SWIG_DivisionByZero,/* PDF_DivisionByZero 6 */
    SWIG_OverflowError,	/* PDF_OverflowError  7 */
    SWIG_SyntaxError,	/* PDF_SyntaxError    8 */
    SWIG_ValueError,	/* PDF_ValueError     9 */
    SWIG_SystemError,	/* PDF_SystemError   10 */
    SWIG_UnknownError,	/* PDF_NonfatalError 11 */ /* PDFlib-special */
    SWIG_UnknownError,	/* PDF_UnknownError  12 */
};

/* SWIG exception handling is currently not thread-safe! */
static jmp_buf		exception_buffer;
static int		exception_status;
static char		error_message[256];

/* Exception handling for SWIG. Note that these are not used for the C API */
#define try		if ((exception_status = setjmp(exception_buffer)) == 0)
#define catch(error)	else if (exception_status == error)
#define throw(error)	longjmp(exception_buffer, error)
#define finally		else

/* PDFlib error handler for the SWIG libraries */

static void
pdf_swig_errorhandler(PDF *p, int type, const char* shortmsg)
{
    sprintf(error_message, "PDFlib: %s\n", shortmsg);

    /* Issue a warning message and continue for non-fatal errors */
    if (type == PDF_NonfatalError) {
	fprintf(stderr, error_message);
	return;
    }
	
    /* Clean up PDFlib internals and delete p in all other cases */
    if (p != NULL)
	PDF_delete(p);

    /* ...and throw an exception */
    throw(type);
}

/* Force the SWIG error handler for all clients */
#define PDF_new() PDF_new2(pdf_swig_errorhandler, NULL, NULL, NULL, NULL)

/* Map PDFlib errors to Java exceptions */
static const char *pdf_java_exceptions[] = {
NULL,
"java/lang/OutOfMemoryError",		/* PDF_MemoryError    1 */
"java/io/IOException",			/* PDF_IOError        2 */
"java/lang/IllegalArgumentException",	/* PDF_RuntimeError   3 */
"java/lang/IndexOutOfBoundsException",	/* PDF_IndexError     4 */
"java/lang/ClassCastException",		/* PDF_TypeError      5 */
"java/lang/ArithmeticException",	/* PDF_DivisionByZero 6 */
"java/lang/ArithmeticException",	/* PDF_OverflowError  7 */
"java/lang/RuntimeException",		/* PDF_SyntaxError    8 */
"java/lang/IllegalArgumentException",	/* PDF_ValueError     9 */
"java/lang/InternalError",		/* PDF_SystemError   10 */
"java/lang/UnknownError",		/* PDF_NonfatalError 11 */
"java/lang/UnknownError",		/* PDF_UnknownError  12 */
};

/* This should come from SWIG but SWIG's experimental Java support
 * currently doesn't cover exceptions.
 */

#define SWIG_exception(type, msg) (*jenv)->ThrowNew(jenv, \
        (*jenv)->FindClass(jenv, pdf_java_exceptions[type]), msg);


/* export the PDFlib routines to the shared library */
#ifdef __MWERKS__
#pragma export on
#endif

JNIEXPORT void JNICALL Java_pdflib_PDF_1boot(JNIEnv *jenv, jclass jcls) {

{
    try {     PDF_boot();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1shutdown(JNIEnv *jenv, jclass jcls) {

{
    try {     PDF_shutdown();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jlong JNICALL Java_pdflib_PDF_1new(JNIEnv *jenv, jclass jcls) {
    jlong _jresult = 0;
    PDF * _result;

{
    try {     _result = (PDF *)PDF_new();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    *(PDF **)&_jresult = _result;
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1delete(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_delete(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1file(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     _result = (int )PDF_open_file(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1close(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_close(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1begin_1page(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_begin_page(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1end_1page(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_end_page(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1parameter(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2) {
    PDF * _arg0;
    char * _arg1;
    char * _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (jarg2) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0) : NULL;
{
    try {     PDF_set_parameter(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    if(_arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, _arg2);
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1findfont(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jint jarg3) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;
    char * _arg2;
    int  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (jarg2) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0) : NULL;
    _arg3 = (int )jarg3;
{
    try {     _result = (int )PDF_findfont(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    if(_arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, _arg2);
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setfont(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1, jfloat jarg2) {
    PDF * _arg0;
    int  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_setfont(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1font(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jfloat jarg2, jstring jarg3) {
    PDF * _arg0;
    char * _arg1;
    float  _arg2;
    char * _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (float )jarg2;
    _arg3 = (jarg3) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0) : NULL;
{
    try {     PDF_set_font(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    if(_arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, _arg3);
}

JNIEXPORT jstring JNICALL Java_pdflib_PDF_1get_1fontname(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    jstring _jresult = 0;
    char * _result;
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     _result = (char *)PDF_get_fontname(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_result != NULL)
        _jresult = (jstring)(*jenv)->NewStringUTF(jenv, _result);
    return _jresult;
}

JNIEXPORT jfloat JNICALL Java_pdflib_PDF_1get_1fontsize(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    jfloat _jresult = 0;
    float  _result;
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     _result = (float )PDF_get_fontsize(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jfloat) _result;
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1get_1font(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     _result = (int )PDF_get_font(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1show(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     PDF_show(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1show_1xy(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    char * _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_show_xy(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1continue_1text(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     PDF_continue_text(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1leading(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_leading(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1text_1rise(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_text_rise(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1horiz_1scaling(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_horiz_scaling(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1text_1rendering(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     PDF_set_text_rendering(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1text_1matrix(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5, jfloat jarg6) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;
    float  _arg6;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (float )jarg5;
    _arg6 = (float )jarg6;
{
    try {     PDF_set_text_matrix(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1text_1pos(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_set_text_pos(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1char_1spacing(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_char_spacing(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1word_1spacing(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_word_spacing(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jfloat JNICALL Java_pdflib_PDF_1stringwidth(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jint jarg2, jfloat jarg3) {
    jfloat _jresult = 0;
    float  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (int )jarg2;
    _arg3 = (float )jarg3;
{
    try {     _result = (float )PDF_stringwidth(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jfloat) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setdash(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_setdash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setpolydash(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloatArray jarg1, jint jarg2) {
    PDF * _arg0;
    float * _arg1;
    int  _arg2;
    jfloat* _arg10;
    jsize _arg11 = (*jenv)->GetArrayLength(jenv, jarg1);
    int i;

    _arg0 = *(PDF **)&jarg0;
    _arg10 = (*jenv)->GetFloatArrayElements(jenv, jarg1, 0);
    _arg1 = (float *) malloc(_arg11 * sizeof(float ));
    for(i=0; i<_arg11; i++)
        _arg1[i] = (float )_arg10[i];
    _arg2 = (int )jarg2;
{
    try {     PDF_setpolydash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    for(i=0; i<_arg11; i++)
        _arg10[i] = (jfloat) _arg1[i];
    (*jenv)->ReleaseFloatArrayElements(jenv, jarg1, _arg10, 0);
    free(_arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setflat(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setflat(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setlinejoin(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     PDF_setlinejoin(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setlinecap(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     PDF_setlinecap(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setmiterlimit(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setmiterlimit(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setlinewidth(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setlinewidth(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1fillrule(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     PDF_set_fillrule(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1save(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_save(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1restore(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_restore(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1translate(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_translate(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1scale(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_scale(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1rotate(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_rotate(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1moveto(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_moveto(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1lineto(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_lineto(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1curveto(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5, jfloat jarg6) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;
    float  _arg6;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (float )jarg5;
    _arg6 = (float )jarg6;
{
    try {     PDF_curveto(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1circle(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_circle(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1arc(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jfloat jarg5) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (float )jarg5;
{
    try {     PDF_arc(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1rect(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
{
    try {     PDF_rect(_arg0,_arg1,_arg2,_arg3,_arg4);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1closepath(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_closepath(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1closepath_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_closepath_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1fill(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_fill(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1fill_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_fill_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1closepath_1fill_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_closepath_fill_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1endpath(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_endpath(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1clip(JNIEnv *jenv, jclass jcls, jlong jarg0) {
    PDF * _arg0;

    _arg0 = *(PDF **)&jarg0;
{
    try {     PDF_clip(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setgray_1fill(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setgray_fill(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setgray_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setgray_stroke(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setgray(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_setgray(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setrgbcolor_1fill(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_setrgbcolor_fill(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setrgbcolor_1stroke(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_setrgbcolor_stroke(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1setrgbcolor(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_setrgbcolor(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1get_1image_1width(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     _result = (int )PDF_get_image_width(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1get_1image_1height(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     _result = (int )PDF_get_image_height(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1place_1image(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4) {
    PDF * _arg0;
    int  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
{
    try {     PDF_place_image(_arg0,_arg1,_arg2,_arg3,_arg4);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1image(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2, jstring jarg3, jlong jarg4, jint jarg5, jint jarg6, jint jarg7, jint jarg8, jstring jarg9) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;
    char * _arg2;
    char * _arg3;
    long  _arg4;
    int  _arg5;
    int  _arg6;
    int  _arg7;
    int  _arg8;
    char * _arg9;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (jarg2) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0) : NULL;
    _arg3 = (jarg3) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0) : NULL;
    _arg4 = (long )jarg4;
    _arg5 = (int )jarg5;
    _arg6 = (int )jarg6;
    _arg7 = (int )jarg7;
    _arg8 = (int )jarg8;
    _arg9 = (jarg9) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg9, 0) : NULL;
{
    try {     _result = (int )PDF_open_image(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    if(_arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, _arg2);
    if(_arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, _arg3);
    if(_arg9) (*jenv)->ReleaseStringUTFChars(jenv, jarg9, _arg9);
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1close_1image(JNIEnv *jenv, jclass jcls, jlong jarg0, jint jarg1) {
    PDF * _arg0;
    int  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (int )jarg1;
{
    try {     PDF_close_image(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1JPEG(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     _result = (int )PDF_open_JPEG(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1TIFF(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     _result = (int )PDF_open_TIFF(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1GIF(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     _result = (int )PDF_open_GIF(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1open_1CCITT(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jint jarg2, jint jarg3, jint jarg4, jint jarg5, jint jarg6) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;
    int  _arg4;
    int  _arg5;
    int  _arg6;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (int )jarg2;
    _arg3 = (int )jarg3;
    _arg4 = (int )jarg4;
    _arg5 = (int )jarg5;
    _arg6 = (int )jarg6;
{
    try {     _result = (int )PDF_open_CCITT(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT jint JNICALL Java_pdflib_PDF_1add_1bookmark(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jint jarg2, jint jarg3) {
    jint _jresult = 0;
    int  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (int )jarg2;
    _arg3 = (int )jarg3;
{
    try {     _result = (int )PDF_add_bookmark(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    _jresult = (jint) _result;
    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    return _jresult;
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1info(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jstring jarg2) {
    PDF * _arg0;
    char * _arg1;
    char * _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (jarg2) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0) : NULL;
{
    try {     PDF_set_info(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
    if(_arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, _arg2);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1transition(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1) {
    PDF * _arg0;
    char * _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
{
    try {     PDF_set_transition(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1duration(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1) {
    PDF * _arg0;
    float  _arg1;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
{
    try {     PDF_set_duration(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1attach_1file(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jstring jarg5, jstring jarg6, jstring jarg7, jstring jarg8, jstring jarg9) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    char * _arg6;
    char * _arg7;
    char * _arg8;
    char * _arg9;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (jarg5) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0) : NULL;
    _arg6 = (jarg6) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0) : NULL;
    _arg7 = (jarg7) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg7, 0) : NULL;
    _arg8 = (jarg8) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg8, 0) : NULL;
    _arg9 = (jarg9) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg9, 0) : NULL;
{
    try {     PDF_attach_file(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, _arg5);
    if(_arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, _arg6);
    if(_arg7) (*jenv)->ReleaseStringUTFChars(jenv, jarg7, _arg7);
    if(_arg8) (*jenv)->ReleaseStringUTFChars(jenv, jarg8, _arg8);
    if(_arg9) (*jenv)->ReleaseStringUTFChars(jenv, jarg9, _arg9);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1add_1note(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jstring jarg5, jstring jarg6, jstring jarg7, jint jarg8) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    char * _arg6;
    char * _arg7;
    int  _arg8;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (jarg5) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0) : NULL;
    _arg6 = (jarg6) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0) : NULL;
    _arg7 = (jarg7) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg7, 0) : NULL;
    _arg8 = (int )jarg8;
{
    try {     PDF_add_note(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, _arg5);
    if(_arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, _arg6);
    if(_arg7) (*jenv)->ReleaseStringUTFChars(jenv, jarg7, _arg7);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1add_1pdflink(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jstring jarg5, jint jarg6, jstring jarg7) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    int  _arg6;
    char * _arg7;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (jarg5) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0) : NULL;
    _arg6 = (int )jarg6;
    _arg7 = (jarg7) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg7, 0) : NULL;
{
    try {     PDF_add_pdflink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, _arg5);
    if(_arg7) (*jenv)->ReleaseStringUTFChars(jenv, jarg7, _arg7);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1add_1launchlink(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jstring jarg5) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (jarg5) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0) : NULL;
{
    try {     PDF_add_launchlink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, _arg5);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1add_1locallink(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jint jarg5, jstring jarg6) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    int  _arg5;
    char * _arg6;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (int )jarg5;
    _arg6 = (jarg6) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg6, 0) : NULL;
{
    try {     PDF_add_locallink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg6) (*jenv)->ReleaseStringUTFChars(jenv, jarg6, _arg6);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1add_1weblink(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3, jfloat jarg4, jstring jarg5) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
    _arg4 = (float )jarg4;
    _arg5 = (jarg5) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg5, 0) : NULL;
{
    try {     PDF_add_weblink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg5) (*jenv)->ReleaseStringUTFChars(jenv, jarg5, _arg5);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1border_1style(JNIEnv *jenv, jclass jcls, jlong jarg0, jstring jarg1, jfloat jarg2) {
    PDF * _arg0;
    char * _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (jarg1) ? (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0) : NULL;
    _arg2 = (float )jarg2;
{
    try {     PDF_set_border_style(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    if(_arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, _arg1);
}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1border_1color(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2, jfloat jarg3) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
    _arg3 = (float )jarg3;
{
    try {     PDF_set_border_color(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

JNIEXPORT void JNICALL Java_pdflib_PDF_1set_1border_1dash(JNIEnv *jenv, jclass jcls, jlong jarg0, jfloat jarg1, jfloat jarg2) {
    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    _arg0 = *(PDF **)&jarg0;
    _arg1 = (float )jarg1;
    _arg2 = (float )jarg2;
{
    try {     PDF_set_border_dash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}}

