/*
 * FILE : pdflib_tcl.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.2 (alpha 1)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : TCL 7.x */

#define INCLUDE_TCL    <tcl.h>
#define INCLUDE_TK     <tk.h>
#include INCLUDE_TCL
#include <string.h>
#include <stdlib.h>
#define SWIGTCL
/*
 * $Header: /usr/local/cvsroot/swig/swig1/swig_lib/tcl/swigtcl.swg,v 1.1.1.1 1999/01/21 11:16:42 harcoh Exp $
 * 
 * swigtcl.cfg
 *
 * This file is modified from a platform independent file provided
 * by Sun.   With any luck this will allow SWIG generated wrapper
 * files to work on Unix, Windows, and Macintosh.
 *
 * Revision History
 * $Log: swigtcl.swg,v $
 * Revision 1.1.1.1  1999/01/21 11:16:42  harcoh
 * import of Swig 1.2a1
 *
 * Revision 1.1  1996/05/22 19:47:45  beazley
 * Initial revision
 *
 *
 * -- Dave Beazley, May 2, 1996.
 *
 *	This file is an example of a Tcl dynamically loadable extension.
 *
 * Copyright (c) 1996 by Sun Microsystems, Inc.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 */

#if defined(__WIN32__)
#   define WIN32_LEAN_AND_MEAN
#   include <windows.h>
#   undef WIN32_LEAN_AND_MEAN

/*
 * VC++ has an alternate entry point called DllMain, so we need to rename
 * our entry point.
 */

#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#	define DllEntryPoint DllMain
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

/*
 *----------------------------------------------------------------------
 *
 * DllEntryPoint --
 *
 *	This wrapper function is used by Windows to invoke the
 *	initialization code for the DLL.  If we are compiling
 *	with Visual C++, this routine will be renamed to DllMain.
 *	routine.
 *
 * Results:
 *	Returns TRUE;
 *
 * Side effects:
 *	None.
 *
 *----------------------------------------------------------------------
 */

#ifdef __WIN32__
BOOL APIENTRY
DllEntryPoint(HINSTANCE hInst, DWORD reason, LPVOID reserved)
{
    return TRUE;
}
#endif

/*****************************************************************************
 * $Header: /usr/local/cvsroot/swig/swig1/swig_lib/swigptr.swg,v 1.1.1.1 1999/01/21 11:16:42 harcoh Exp $
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    Pdflib_Init


#ifdef __cplusplus
extern "C" {
#endif
#ifdef MAC_TCL
#pragma export on
#endif
SWIGEXPORT(int,Pdflib_Init)(Tcl_Interp *);
#ifdef MAC_TCL
#pragma export off
#endif
#ifdef __cplusplus
}
#endif

#define  SWIG_MemoryError    1
#define  SWIG_IOError        2
#define  SWIG_RuntimeError   3
#define  SWIG_IndexError     4
#define  SWIG_TypeError      5
#define  SWIG_DivisionByZero 6
#define  SWIG_OverflowError  7
#define  SWIG_SyntaxError    8
#define  SWIG_ValueError     9
#define  SWIG_SystemError   10
#define  SWIG_UnknownError  99

#define SWIG_exception(a,b)   Tcl_SetResult(interp,b,TCL_VOLATILE); return TCL_ERROR

#include <setjmp.h>

/* The following sick stuff is an attempt to make recent Perl versions
 * work with recent SWIG versions compiled with recent MS VC++ versions.
 */
#ifdef _MSC_VER
    #undef setjmp
    #define setjmp _setjmp
    #undef longjmp
#endif

#include "pdflib.h"

/* Map PDFlib errors to SWIG exceptions */
static const int pdf_swig_exceptions[] = {
    0,
    SWIG_MemoryError,	/* PDF_MemoryError    1 */
    SWIG_IOError,	/* PDF_IOError        2 */
    SWIG_RuntimeError,	/* PDF_RuntimeError   3 */
    SWIG_IndexError,	/* PDF_IndexError     4 */
    SWIG_TypeError,	/* PDF_TypeError      5 */
    SWIG_DivisionByZero,/* PDF_DivisionByZero 6 */
    SWIG_OverflowError,	/* PDF_OverflowError  7 */
    SWIG_SyntaxError,	/* PDF_SyntaxError    8 */
    SWIG_ValueError,	/* PDF_ValueError     9 */
    SWIG_SystemError,	/* PDF_SystemError   10 */
    SWIG_UnknownError,	/* PDF_NonfatalError 11 */ /* PDFlib-special */
    SWIG_UnknownError,	/* PDF_UnknownError  12 */
};

/* SWIG exception handling is currently not thread-safe! */
static jmp_buf		exception_buffer;
static int		exception_status;
static char		error_message[256];

/* Exception handling for SWIG. Note that these are not used for the C API */
#define try		if ((exception_status = setjmp(exception_buffer)) == 0)
#define catch(error)	else if (exception_status == error)
#define throw(error)	longjmp(exception_buffer, error)
#define finally		else

/* PDFlib error handler for the SWIG libraries */

static void
pdf_swig_errorhandler(PDF *p, int type, const char* shortmsg)
{
    sprintf(error_message, "PDFlib: %s\n", shortmsg);

    /* Issue a warning message and continue for non-fatal errors */
    if (type == PDF_NonfatalError) {
	fprintf(stderr, error_message);
	return;
    }
	
    /* Clean up PDFlib internals and delete p in all other cases */
    if (p != NULL)
	PDF_delete(p);

    /* ...and throw an exception */
    throw(type);
}

/* Force the SWIG error handler for all clients */
#define PDF_new() PDF_new2(pdf_swig_errorhandler, NULL, NULL, NULL, NULL)

/* export the PDFlib routines to the shared library */
#ifdef __MWERKS__
#pragma export on
#endif

static int _wrap_PDF_boot(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {


    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_boot ",TCL_STATIC);
        return TCL_ERROR;
    }
{
    try {     PDF_boot();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_shutdown(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {


    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_shutdown ",TCL_STATIC);
        return TCL_ERROR;
    }
{
    try {     PDF_shutdown();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_new(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _result;

    clientData = clientData; argv = argv;
    if ((argc < 1) || (argc > 1)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_new ",TCL_STATIC);
        return TCL_ERROR;
    }
{
    try {     _result = (PDF *)PDF_new();
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    SWIG_MakePtr(interp->result, (void *) _result,"_PDF_p");
    return TCL_OK;
}
static int _wrap_PDF_delete(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_delete p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_delete. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_delete(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_open_file(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_file p filename ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_file. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     _result = (int )PDF_open_file(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_close(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_close p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_close. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_close(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_begin_page(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_begin_page p width height ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_begin_page. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_begin_page(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_end_page(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_end_page p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_end_page. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_end_page(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_parameter(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_parameter p key value ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_parameter. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
{
    try {     PDF_set_parameter(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_findfont(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;
    char * _arg2;
    int  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_findfont p fontname encoding embed ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_findfont. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    _arg3 = (int ) atol(argv[4]);
{
    try {     _result = (int )PDF_findfont(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_setfont(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setfont p font fontsize ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setfont. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_setfont(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_font(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;
    float  _arg2;
    char * _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_font p fontname fontsize encoding ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_font. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (float ) atof(argv[3]);
    _arg3 = argv[4];
{
    try {     PDF_set_font(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_get_fontname(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    char * _result;
    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_get_fontname p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_get_fontname. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     _result = (char *)PDF_get_fontname(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    Tcl_SetResult(interp, (char *) _result, TCL_VOLATILE);
    return TCL_OK;
}
static int _wrap_PDF_get_fontsize(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    float  _result;
    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_get_fontsize p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_get_fontsize. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     _result = (float )PDF_get_fontsize(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    Tcl_PrintDouble(interp,(double) _result, interp->result);
    return TCL_OK;
}
static int _wrap_PDF_get_font(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_get_font p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_get_font. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     _result = (int )PDF_get_font(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_show(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_show p text ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_show. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     PDF_show(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_show_xy(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_show_xy p text x y ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_show_xy. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_show_xy(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_continue_text(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_continue_text p text ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_continue_text. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     PDF_continue_text(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_leading(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_leading p leading ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_leading. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_leading(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_text_rise(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_text_rise p rise ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_text_rise. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_text_rise(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_horiz_scaling(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_horiz_scaling p scale ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_horiz_scaling. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_horiz_scaling(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_text_rendering(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_text_rendering p mode ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_text_rendering. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     PDF_set_text_rendering(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_text_matrix(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;
    float  _arg6;

    clientData = clientData; argv = argv;
    if ((argc < 8) || (argc > 8)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_text_matrix p a b c d e f ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_text_matrix. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = (float ) atof(argv[6]);
    _arg6 = (float ) atof(argv[7]);
{
    try {     PDF_set_text_matrix(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_text_pos(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_text_pos p x y ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_text_pos. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_set_text_pos(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_char_spacing(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_char_spacing p spacing ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_char_spacing. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_char_spacing(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_word_spacing(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_word_spacing p spacing ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_word_spacing. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_word_spacing(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_stringwidth(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    float  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_stringwidth p text font size ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_stringwidth. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (int ) atol(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     _result = (float )PDF_stringwidth(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    Tcl_PrintDouble(interp,(double) _result, interp->result);
    return TCL_OK;
}
static int _wrap_PDF_setdash(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setdash p b w ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setdash. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_setdash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setpolydash(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float * _arg1;
    int  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setpolydash p darray length ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setpolydash. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[2],(void **) &_arg1,"_float_p")) {
        Tcl_SetResult(interp, "Type error in argument 2 of PDF_setpolydash. Expected _float_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[2], (char *) NULL);
        return TCL_ERROR;
    }
    _arg2 = (int ) atol(argv[3]);
{
    try {     PDF_setpolydash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setflat(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setflat p flatness ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setflat. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setflat(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setlinejoin(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setlinejoin p linejoin ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setlinejoin. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     PDF_setlinejoin(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setlinecap(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setlinecap p linecap ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setlinecap. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     PDF_setlinecap(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setmiterlimit(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setmiterlimit p miter ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setmiterlimit. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setmiterlimit(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setlinewidth(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setlinewidth p width ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setlinewidth. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setlinewidth(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_fillrule(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_fillrule p fillrule ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_fillrule. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     PDF_set_fillrule(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_save(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_save p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_save. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_save(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_restore(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_restore p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_restore. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_restore(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_translate(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_translate p tx ty ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_translate. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_translate(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_scale(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_scale p sx sy ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_scale. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_scale(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_rotate(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_rotate p phi ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_rotate. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_rotate(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_moveto(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_moveto p x y ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_moveto. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_moveto(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_lineto(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_lineto p x y ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_lineto. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_lineto(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_curveto(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;
    float  _arg6;

    clientData = clientData; argv = argv;
    if ((argc < 8) || (argc > 8)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_curveto p x1 y1 x2 y2 x3 y3 ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_curveto. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = (float ) atof(argv[6]);
    _arg6 = (float ) atof(argv[7]);
{
    try {     PDF_curveto(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_circle(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_circle p x y r ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_circle. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_circle(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_arc(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    float  _arg5;

    clientData = clientData; argv = argv;
    if ((argc < 7) || (argc > 7)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_arc p x y r alpha1 alpha2 ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_arc. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = (float ) atof(argv[6]);
{
    try {     PDF_arc(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_rect(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;

    clientData = clientData; argv = argv;
    if ((argc < 6) || (argc > 6)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_rect p x y width height ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_rect. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
{
    try {     PDF_rect(_arg0,_arg1,_arg2,_arg3,_arg4);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_closepath(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_closepath p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_closepath. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_closepath(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_stroke p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_closepath_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_closepath_stroke p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_closepath_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_closepath_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_fill(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_fill p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_fill. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_fill(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_fill_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_fill_stroke p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_fill_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_fill_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_closepath_fill_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_closepath_fill_stroke p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_closepath_fill_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_closepath_fill_stroke(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_endpath(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_endpath p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_endpath. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_endpath(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_clip(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;

    clientData = clientData; argv = argv;
    if ((argc < 2) || (argc > 2)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_clip p ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_clip. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
{
    try {     PDF_clip(_arg0);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setgray_fill(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setgray_fill p g ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setgray_fill. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setgray_fill(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setgray_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setgray_stroke p g ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setgray_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setgray_stroke(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setgray(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setgray p g ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setgray. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_setgray(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setrgbcolor_fill(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setrgbcolor_fill p red green blue ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setrgbcolor_fill. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_setrgbcolor_fill(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setrgbcolor_stroke(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setrgbcolor_stroke p red green blue ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setrgbcolor_stroke. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_setrgbcolor_stroke(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_setrgbcolor(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_setrgbcolor p red green blue ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_setrgbcolor. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_setrgbcolor(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_get_image_width(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_get_image_width p image ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_get_image_width. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     _result = (int )PDF_get_image_width(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_get_image_height(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_get_image_height p image ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_get_image_height. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     _result = (int )PDF_get_image_height(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_place_image(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;

    clientData = clientData; argv = argv;
    if ((argc < 6) || (argc > 6)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_place_image p image x y scale ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_place_image. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
{
    try {     PDF_place_image(_arg0,_arg1,_arg2,_arg3,_arg4);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_open_image(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;
    char * _arg2;
    char * _arg3;
    long  _arg4;
    int  _arg5;
    int  _arg6;
    int  _arg7;
    int  _arg8;
    char * _arg9;

    clientData = clientData; argv = argv;
    if ((argc < 11) || (argc > 11)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_image p type source data length width height components bpc params ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_image. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
    _arg3 = argv[4];
    _arg4 = (long ) atol(argv[5]);
    _arg5 = (int ) atol(argv[6]);
    _arg6 = (int ) atol(argv[7]);
    _arg7 = (int ) atol(argv[8]);
    _arg8 = (int ) atol(argv[9]);
    _arg9 = argv[10];
{
    try {     _result = (int )PDF_open_image(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_close_image(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    int  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_close_image p image ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_close_image. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (int ) atol(argv[2]);
{
    try {     PDF_close_image(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_open_JPEG(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_JPEG p filename ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_JPEG. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     _result = (int )PDF_open_JPEG(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_open_TIFF(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_TIFF p filename ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_TIFF. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     _result = (int )PDF_open_TIFF(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_open_GIF(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_GIF p filename ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_GIF. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     _result = (int )PDF_open_GIF(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_open_CCITT(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;
    int  _arg4;
    int  _arg5;
    int  _arg6;

    clientData = clientData; argv = argv;
    if ((argc < 8) || (argc > 8)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_open_CCITT p filename width height BitReverse K BlackIs1 ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_open_CCITT. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (int ) atol(argv[3]);
    _arg3 = (int ) atol(argv[4]);
    _arg4 = (int ) atol(argv[5]);
    _arg5 = (int ) atol(argv[6]);
    _arg6 = (int ) atol(argv[7]);
{
    try {     _result = (int )PDF_open_CCITT(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_add_bookmark(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    int  _result;
    PDF * _arg0;
    char * _arg1;
    int  _arg2;
    int  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_bookmark p text parent open ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_bookmark. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (int ) atol(argv[3]);
    _arg3 = (int ) atol(argv[4]);
{
    try {     _result = (int )PDF_add_bookmark(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    sprintf(interp->result,"%ld", (long) _result);
    return TCL_OK;
}
static int _wrap_PDF_set_info(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;
    char * _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_info p key value ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_info. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = argv[3];
{
    try {     PDF_set_info(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_transition(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_transition p type ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_transition. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
{
    try {     PDF_set_transition(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_duration(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;

    clientData = clientData; argv = argv;
    if ((argc < 3) || (argc > 3)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_duration p t ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_duration. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
{
    try {     PDF_set_duration(_arg0,_arg1);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_attach_file(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    char * _arg6;
    char * _arg7;
    char * _arg8;
    char * _arg9;

    clientData = clientData; argv = argv;
    if ((argc < 11) || (argc > 11)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_attach_file p llx lly urx ury filename description author mimetype icon ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_attach_file. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = argv[6];
    _arg6 = argv[7];
    _arg7 = argv[8];
    _arg8 = argv[9];
    _arg9 = argv[10];
{
    try {     PDF_attach_file(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_add_note(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    char * _arg6;
    char * _arg7;
    int  _arg8;

    clientData = clientData; argv = argv;
    if ((argc < 10) || (argc > 10)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_note p llx lly urx ury contents title icon open ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_note. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = argv[6];
    _arg6 = argv[7];
    _arg7 = argv[8];
    _arg8 = (int ) atol(argv[9]);
{
    try {     PDF_add_note(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_add_pdflink(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;
    int  _arg6;
    char * _arg7;

    clientData = clientData; argv = argv;
    if ((argc < 9) || (argc > 9)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_pdflink p llx lly urx ury filename page dest ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_pdflink. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = argv[6];
    _arg6 = (int ) atol(argv[7]);
    _arg7 = argv[8];
{
    try {     PDF_add_pdflink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_add_launchlink(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;

    clientData = clientData; argv = argv;
    if ((argc < 7) || (argc > 7)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_launchlink p llx lly urx ury filename ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_launchlink. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = argv[6];
{
    try {     PDF_add_launchlink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_add_locallink(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    int  _arg5;
    char * _arg6;

    clientData = clientData; argv = argv;
    if ((argc < 8) || (argc > 8)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_locallink p llx lly urx ury page dest ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_locallink. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = (int ) atol(argv[6]);
    _arg6 = argv[7];
{
    try {     PDF_add_locallink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_add_weblink(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;
    float  _arg4;
    char * _arg5;

    clientData = clientData; argv = argv;
    if ((argc < 7) || (argc > 7)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_add_weblink p llx lly urx ury url ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_add_weblink. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
    _arg4 = (float ) atof(argv[5]);
    _arg5 = argv[6];
{
    try {     PDF_add_weblink(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_border_style(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    char * _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_border_style p style width ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_border_style. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = argv[2];
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_set_border_style(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_border_color(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;
    float  _arg3;

    clientData = clientData; argv = argv;
    if ((argc < 5) || (argc > 5)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_border_color p red green blue ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_border_color. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
    _arg3 = (float ) atof(argv[4]);
{
    try {     PDF_set_border_color(_arg0,_arg1,_arg2,_arg3);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
static int _wrap_PDF_set_border_dash(ClientData clientData, Tcl_Interp *interp, int argc, char *argv[]) {

    PDF * _arg0;
    float  _arg1;
    float  _arg2;

    clientData = clientData; argv = argv;
    if ((argc < 4) || (argc > 4)) {
        Tcl_SetResult(interp, "Wrong # args. PDF_set_border_dash p w b ",TCL_STATIC);
        return TCL_ERROR;
    }
    if (SWIG_GetPtr(argv[1],(void **) &_arg0,"_PDF_p")) {
        Tcl_SetResult(interp, "Type error in argument 1 of PDF_set_border_dash. Expected _PDF_p, received ", TCL_STATIC);
        Tcl_AppendResult(interp, argv[1], (char *) NULL);
        return TCL_ERROR;
    }
    _arg1 = (float ) atof(argv[2]);
    _arg2 = (float ) atof(argv[3]);
{
    try {     PDF_set_border_dash(_arg0,_arg1,_arg2);
 }
    else {
	SWIG_exception(pdf_swig_exceptions[exception_status], error_message);
    }
}    return TCL_OK;
}
SWIGEXPORT(int,Pdflib_Init)(Tcl_Interp *interp) {
	 if (interp == 0) 
		 return TCL_ERROR;

	/* Boot the PDFlib core */
	PDF_boot();

	/* Tell Tcl which package we are going to define */
	Tcl_PkgProvide(interp, "pdflib", PDFLIB_VERSIONSTRING);
	 Tcl_CreateCommand(interp, "PDF_boot", _wrap_PDF_boot, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_shutdown", _wrap_PDF_shutdown, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_new", _wrap_PDF_new, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_delete", _wrap_PDF_delete, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_file", _wrap_PDF_open_file, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_close", _wrap_PDF_close, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_begin_page", _wrap_PDF_begin_page, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_end_page", _wrap_PDF_end_page, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_parameter", _wrap_PDF_set_parameter, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_findfont", _wrap_PDF_findfont, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setfont", _wrap_PDF_setfont, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_font", _wrap_PDF_set_font, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_get_fontname", _wrap_PDF_get_fontname, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_get_fontsize", _wrap_PDF_get_fontsize, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_get_font", _wrap_PDF_get_font, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_show", _wrap_PDF_show, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_show_xy", _wrap_PDF_show_xy, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_continue_text", _wrap_PDF_continue_text, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_leading", _wrap_PDF_set_leading, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_text_rise", _wrap_PDF_set_text_rise, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_horiz_scaling", _wrap_PDF_set_horiz_scaling, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_text_rendering", _wrap_PDF_set_text_rendering, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_text_matrix", _wrap_PDF_set_text_matrix, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_text_pos", _wrap_PDF_set_text_pos, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_char_spacing", _wrap_PDF_set_char_spacing, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_word_spacing", _wrap_PDF_set_word_spacing, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_stringwidth", _wrap_PDF_stringwidth, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setdash", _wrap_PDF_setdash, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setpolydash", _wrap_PDF_setpolydash, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setflat", _wrap_PDF_setflat, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setlinejoin", _wrap_PDF_setlinejoin, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setlinecap", _wrap_PDF_setlinecap, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setmiterlimit", _wrap_PDF_setmiterlimit, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setlinewidth", _wrap_PDF_setlinewidth, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_fillrule", _wrap_PDF_set_fillrule, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_save", _wrap_PDF_save, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_restore", _wrap_PDF_restore, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_translate", _wrap_PDF_translate, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_scale", _wrap_PDF_scale, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_rotate", _wrap_PDF_rotate, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_moveto", _wrap_PDF_moveto, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_lineto", _wrap_PDF_lineto, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_curveto", _wrap_PDF_curveto, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_circle", _wrap_PDF_circle, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_arc", _wrap_PDF_arc, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_rect", _wrap_PDF_rect, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_closepath", _wrap_PDF_closepath, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_stroke", _wrap_PDF_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_closepath_stroke", _wrap_PDF_closepath_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_fill", _wrap_PDF_fill, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_fill_stroke", _wrap_PDF_fill_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_closepath_fill_stroke", _wrap_PDF_closepath_fill_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_endpath", _wrap_PDF_endpath, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_clip", _wrap_PDF_clip, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setgray_fill", _wrap_PDF_setgray_fill, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setgray_stroke", _wrap_PDF_setgray_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setgray", _wrap_PDF_setgray, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setrgbcolor_fill", _wrap_PDF_setrgbcolor_fill, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setrgbcolor_stroke", _wrap_PDF_setrgbcolor_stroke, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_setrgbcolor", _wrap_PDF_setrgbcolor, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_get_image_width", _wrap_PDF_get_image_width, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_get_image_height", _wrap_PDF_get_image_height, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_place_image", _wrap_PDF_place_image, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_image", _wrap_PDF_open_image, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_close_image", _wrap_PDF_close_image, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_JPEG", _wrap_PDF_open_JPEG, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_TIFF", _wrap_PDF_open_TIFF, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_GIF", _wrap_PDF_open_GIF, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_open_CCITT", _wrap_PDF_open_CCITT, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_bookmark", _wrap_PDF_add_bookmark, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_info", _wrap_PDF_set_info, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_transition", _wrap_PDF_set_transition, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_duration", _wrap_PDF_set_duration, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_attach_file", _wrap_PDF_attach_file, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_note", _wrap_PDF_add_note, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_pdflink", _wrap_PDF_add_pdflink, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_launchlink", _wrap_PDF_add_launchlink, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_locallink", _wrap_PDF_add_locallink, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_add_weblink", _wrap_PDF_add_weblink, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_border_style", _wrap_PDF_set_border_style, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_border_color", _wrap_PDF_set_border_color, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
	 Tcl_CreateCommand(interp, "PDF_set_border_dash", _wrap_PDF_set_border_dash, (ClientData) NULL, (Tcl_CmdDeleteProc *) NULL);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_struct_PDF_s","_PDF",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_PDF","_struct_PDF_s",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
	 return TCL_OK;
}
