# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded pdflib 2.01 [list tclPkgSetup $dir pdflib 2.01 {{pdflib.so load {PDF_add_bookmark PDF_add_launchlink PDF_add_locallink PDF_add_note PDF_add_pdflink PDF_add_weblink PDF_arc PDF_attach_file PDF_begin_page PDF_boot PDF_circle PDF_clip PDF_close PDF_close_image PDF_closepath PDF_closepath_fill_stroke PDF_closepath_stroke PDF_continue_text PDF_curveto PDF_delete PDF_end_page PDF_endpath PDF_fill PDF_fill_stroke PDF_findfont PDF_get_font PDF_get_fontname PDF_get_fontsize PDF_get_image_height PDF_get_image_width PDF_lineto PDF_moveto PDF_new PDF_open_CCITT PDF_open_GIF PDF_open_JPEG PDF_open_TIFF PDF_open_file PDF_open_image PDF_place_image PDF_rect PDF_restore PDF_rotate PDF_save PDF_scale PDF_set_border_color PDF_set_border_dash PDF_set_border_style PDF_set_char_spacing PDF_set_duration PDF_set_fillrule PDF_set_font PDF_set_horiz_scaling PDF_set_info PDF_set_leading PDF_set_parameter PDF_set_text_matrix PDF_set_text_pos PDF_set_text_rendering PDF_set_text_rise PDF_set_transition PDF_set_word_spacing PDF_setdash PDF_setflat PDF_setfont PDF_setgray PDF_setgray_fill PDF_setgray_stroke PDF_setlinecap PDF_setlinejoin PDF_setlinewidth PDF_setmiterlimit PDF_setpolydash PDF_setrgbcolor PDF_setrgbcolor_fill PDF_setrgbcolor_stroke PDF_show PDF_show_xy PDF_shutdown PDF_stringwidth PDF_stroke PDF_translate}}}]
